# Extracted Python code cells from main.ipynb
# Generated by assistant — contains only code cells in original order.

# --- Cell 2 ---
# file and data handling
from pathlib import Path
import pandas as pd
import numpy as np

# plotting
import matplotlib.pyplot as plt
import seaborn as sns

# model selection and evaluation
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV,
    RandomizedSearchCV,
    learning_curve
)
from sklearn.metrics import root_mean_squared_error, r2_score

# models
from sklearn.linear_model import LinearRegression, PoissonRegressor, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

# preprocessing and pipelines
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer

# other ml libraries
import xgboost as xgb


# --- Cell 6 ---
# Load bike counter data
bike_data = pd.read_parquet(Path("data") / "train.parquet")
bike_data.head()


# --- Cell 8 ---
bike_data.info()


# --- Cell 9 ---
bike_data.describe()


# --- Cell 10 ---
print("Missing values in bike data")
print(bike_data.isna().sum())


# --- Cell 12 ---
import holidays

# Define French holidays
FR_holidays = holidays.FR(years=range(2019, 2022))

bike_data["FR_holidays"] = bike_data["date"].dt.date.isin(FR_holidays).astype(int)
print(f"Number of rows marked as holidays: {bike_data['FR_holidays'].sum()}")


# --- Cell 15 ---
def encode_dates(X):
    X = X.copy()  # Ensure we're working on a copy
    # Encode the date information
    X["year"] = X["date"].dt.year
    X["month"] = X["date"].dt.month
    X["day"] = X["date"].dt.day
    X["weekday"] = X["date"].dt.weekday  # 0=Monday, 6=Sunday
    X["hour"] = X["date"].dt.hour

    # add weekend column
    X["weekend"] = X["weekday"].isin([5, 6]).astype(int)

    return X

# apply date encoding to the bike data
bike_data = encode_dates(bike_data)

# get timesteps from data
print(f'{bike_data["date"].iloc[1] - bike_data["date"].iloc[0]}')


# --- Cell 16 ---
bike_data.head()


# --- Cell 18 ---
weather_data = pd.read_csv(Path("data") / "external_data.csv")
weather_data.head()


# --- Cell 19 ---
print(f"Weather data shape: {weather_data.shape}")
print(weather_data.columns.tolist())


# --- Cell 20 ---
weather_data.info()


# --- Cell 22 ---
weather_data["date"] = pd.to_datetime(weather_data["date"], errors="coerce")


# --- Cell 23 ---
# Check missing values in weather data
missing_pct = (weather_data.isna().sum() / len(weather_data) * 100).round(2)
missing_df = pd.DataFrame({
    'Missing Count': weather_data.isna().sum(),
    'Missing %': missing_pct
}).sort_values('Missing %', ascending=False)

print("Missing values in weather data (sorted by % missing):")
print(missing_df[missing_df['Missing Count'] > 0].head(20))


# --- Cell 27 ---
# Interpolate linearly to get from 3 hour data to 1 hour data
# Set date as index and resample to hourly
weather_data = weather_data.reset_index()
weather_data = weather_data.drop_duplicates(subset="date")
weather_data = weather_data.set_index('date')
weather_data = weather_data.resample('h').interpolate(method='linear')
weather_data = weather_data.reset_index()

# Check new datashape
print(f"Weather data shape after resampling: {weather_data.shape}")


# --- Cell 29 ---
# Merge bike data with weather data using a left join
merged_data = pd.merge(bike_data, weather_data, on="date", how="left")

# Drop redundant date columns to avoid duplicates in the final dataset
merged_data = merged_data.loc[:, ~merged_data.columns.str.endswith(("_x", "_y"))]  # Change 1: Drop `_x` or `_y` suffix columns


# --- Cell 30 ---
from sklearn.preprocessing import FunctionTransformer

date_encoder = FunctionTransformer(encode_dates, validate=False)
sample_encoded = date_encoder.fit_transform(merged_data[["date"]]).head()
sample_encoded


# --- Cell 31 ---
# Reapply the _encode_dates function to extract date-related columns
merged_data = encode_dates(merged_data)

# Verify the new columns
print(merged_data[["date", "year", "month", "day", "weekday", "weekend"]].head())


# --- Cell 32 ---
print(merged_data.shape)


# --- Cell 36 ---
# Check for missing values after merge
missing_after_merge = merged_data.isna().sum()
missing_cols = missing_after_merge[missing_after_merge > 0]
print(f"Columns with missing values after merge: {len(missing_cols)}")
print(missing_cols.sort_values(ascending=False).head(15))


# --- Cell 42 ---
# Convert temperature from Kelvin to Celsius
merged_data['temp_celsius'] = merged_data['t'] - 273.15

# Create temperature squared (captures non-linear relationship)
merged_data['temp_squared'] = merged_data['temp_celsius'] ** 2


# --- Cell 44 ---
# Create season feature (meteorological seasons)
def get_season(month):
    if month in [12, 1, 2]:
        return 0  # Winter
    elif month in [3, 4, 5]:
        return 1  # Spring
    elif month in [6, 7, 8]:
        return 2  # Summer
    else:
        return 3  # Autumn

# Create day phases 
def _add_time_phases(X: pd.DataFrame) -> pd.DataFrame:
    """Add a categorical 'time_of_day' feature based on the hour of day."""
    X = X.copy()
    # Create the 'time_of_day' categorical variable
    X["time_of_day"] = pd.cut(
        X["hour"],
        bins=[0, 5, 9, 13, 17, 20, 23],
        labels=["Night", "Morning", "Midday", "Afternoon", "Evening", "Late Evening"],
        right=True,
    )
    return X


# --- Cell 49 ---
# Apply the function to the dataset
bike_data = _add_time_phases(bike_data)

# Quick preview
bike_data[["hour", "time_of_day"]].head()


# --- Cell 50 ---
merged_data['season'] = merged_data['month'].apply(get_season)

# Cyclical encoding for season (4-season cycle)
merged_data['season_sin'] = np.sin(2 * np.pi * merged_data['season'] / 4)
merged_data['season_cos'] = np.cos(2 * np.pi * merged_data['season'] / 4)

# Season distribution
print("Season distribution:")
print(merged_data['season'].value_counts().sort_index())
print("\n0=Winter, 1=Spring, 2=Summer, 3=Autumn")

# Show cyclical encoding
print("\nSeason cyclical encoding:")
print(merged_data[['season', 'season_sin', 'season_cos']].drop_duplicates().sort_values('season'))


# --- Cell 56 ---
# Mean and median by time-of-day phase
time_of_day_stats = bike_data.groupby("time_of_day")["log_bike_count"].agg(["mean", "median"]).reset_index()

# Mean by hour of day
hourly_stats = bike_data.groupby("hour")["log_bike_count"].mean().reset_index()

# Two subplots: hourly mean and phase mean
fig, ax = plt.subplots(2, 1, figsize=(8, 8), sharey=True)

# Plot hourly mean
ax[0].plot(hourly_stats["hour"], hourly_stats["log_bike_count"], label="Hourly Mean", marker="o")
ax[0].set_title("Hourly Mean of Log Bike Count")
ax[0].set_ylabel("Log Bike Count")
ax[0].set_xlabel("Hour of the Day")
ax[0].grid(True)

# Plot time-of-day mean as bar chart
time_of_day_stats.plot(
    x="time_of_day",
    y="mean",
    kind="bar",
    ax=ax[1],
    color="red",
    legend=False,
    edgecolor="black",
)
ax[1].set_title("Time of Day Mean of Log Bike Count")
ax[1].set_ylabel("Log Bike Count")
ax[1].set_xlabel("Time of Day")
ax[1].set_xticks(range(len(time_of_day_stats["time_of_day"])))
ax[1].set_xticklabels(time_of_day_stats["time_of_day"], rotation=45)

plt.tight_layout()
plt.show()


# --- Cell 58 ---
def _encode_cyclical_features(X: pd.DataFrame, time_unit: str) -> pd.DataFrame:
    # copy the dataframe
    X = X.copy()
    if time_unit == "hour":
        X['hour_sin'] = np.sin(2 * np.pi * X['hour'] / 24)
        X['hour_cos'] = np.cos(2 * np.pi * X['hour'] / 24)
    elif time_unit == "weekday":
        X['weekday_sin'] = np.sin(2 * np.pi * X['weekday'] / 7)
        X['weekday_cos'] = np.cos(2 * np.pi * X['weekday'] / 7)
    elif time_unit == "month":
        X['month_sin'] = np.sin(2 * np.pi * X['month'] / 12)
        X['month_cos'] = np.cos(2 * np.pi * X['month'] / 12)
    elif time_unit == "season":
        X['season_sin'] = np.sin(2 * np.pi * X['season'] / 4)
        X['season_cos'] = np.cos(2 * np.pi * X['season'] / 4)
    return X


# --- Cell 59 ---
# Apply cyclical encoding to the data
merged_data = _encode_cyclical_features(merged_data, "hour")
merged_data = _encode_cyclical_features(merged_data, "weekday")
merged_data = _encode_cyclical_features(merged_data, "month")
merged_data = _encode_cyclical_features(merged_data, "season")


merged_data[['hour', 'hour_sin', 'hour_cos', 'weekday', 'weekday_sin', 'weekday_cos']].head(10)


# --- Cell 62 ---
# Define target columns
target_col_raw = 'bike_count'
target_col_log = 'log_bike_count'

# Temporal split: last 30 days for validation
cutoff_date = merged_data['date'].max() - pd.Timedelta("30 days")
mask = merged_data['date'] < cutoff_date

# Split features (X) and targets (y)
X_train = merged_data[mask].copy()
X_val = merged_data[~mask].copy()

y_train_raw = merged_data.loc[mask, target_col_raw]
y_train_log = merged_data.loc[mask, target_col_log]
y_val_raw = merged_data.loc[~mask, target_col_raw]
y_val_log = merged_data.loc[~mask, target_col_log]

print(f"Training set:   {X_train.shape[0]:,} samples ({X_train['date'].min().date()} to {X_train['date'].max().date()})")
print(f"Validation set: {X_val.shape[0]:,} samples ({X_val['date'].min().date()} to {X_val['date'].max().date()})")


# --- Cell 64 ---
# Column definitions
categorical_cols = ["counter_name", "site_name"]
numerical_cols = ["t", "u", "ff", "td", "rr1", "pmer"]
binary_cols = ["weekend", "FR_holidays"]
cyclical_cols = ["hour_sin", "hour_cos", "weekday_sin", "weekday_cos", "month_sin", "month_cos", "season_sin", "season_cos"]

# Preprocessor
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(), categorical_cols),
    ("num", make_pipeline(SimpleImputer(strategy="mean"), StandardScaler()), numerical_cols),
    ("binary", "passthrough", binary_cols),
    ("cyclical", "passthrough", cyclical_cols)
])


# --- Cell 66 ---
ols = LinearRegression()

pipe_linear = make_pipeline(preprocessor, ols)
pipe_linear.fit(X_train, y_train_log)
y_pred_train_linear = pipe_linear.predict(X_train)
y_pred_val_linear = pipe_linear.predict(X_val)

# Evaluate
train_rmse_linear = root_mean_squared_error(y_train_log, y_pred_train_linear)
val_rmse_linear = root_mean_squared_error(y_val_log, y_pred_val_linear)
print(f"Linear Regression - Train RMSE: {train_rmse_linear:.6f}, Valid RMSE: {val_rmse_linear:.3f}")


# --- Cell 69 ---
residuals = y_train_log - y_pred_train_linear
plt.figure(figsize=(8, 5))
sns.histplot(residuals, kde=True, bins=50) 
plt.title("Distribution of Residuals (Normality Check)")
plt.xlabel("Residual Error (Log Scale)")
plt.ylabel("Frequency")
plt.axvline(x=0, color='red', linestyle='--')
plt.show()


# --- Cell 70 ---
feature_cols = ["hour", "weekday", "month", "season", "t", "u", "ff", "td", "rr1", "pmer", "weekend", "FR_holidays"]

# create train and validaiton set
cutoff_date = merged_data['date'].max() - pd.Timedelta("30 days")
mask = merged_data['date'] < cutoff_date
X_train = merged_data[mask][feature_cols]

y_train_raw = merged_data[mask][target_col_raw]
y_train_log = merged_data[mask][target_col_log]

plt.scatter(y_pred_train_linear, y_axis, alpha=0.3)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted (Log Scale)")
plt.ylabel("Residuals (Log Scale)")
plt.title("Residual Plot (Log Space)")
plt.show()


# --- Cell 72 ---
ridge = Ridge()

X_val = merged_data[~mask][feature_cols]

y_val_raw = merged_data[~mask][target_col_raw]
y_val_log = merged_data[~mask][target_col_log]

date_cols = encode_dates(X_train[["date"]]).columns.tolist()


# --- Cell 75 ---
from sklearn.linear_model import RidgeCV

alphas = np.logspace(-4, 4, 100)

ridge_cv = RidgeCV(alphas=alphas, cv=5)  # 5-fold cross-validation
pipe = make_pipeline(preprocessor, ridge_cv)
pipe.fit(X_train, y_train_log)

print(f"Best alpha: {pipe.named_steps['ridgecv'].alpha_:.4f}")
print(f"Valid RMSE: {root_mean_squared_error(y_val_log, pipe.predict(X_val)):.3f}")


# --- Cell 76 ---
poisson = PoissonRegressor(alpha=1e-3, max_iter=500)

pipe = make_pipeline(preprocessor, poisson)
pipe.fit(X_train, y_train_raw)

# Evaluate
train_rmse = root_mean_squared_error(y_train_log, pipe.predict(X_train))
val_rmse = root_mean_squared_error(y_val_log, pipe.predict(X_val))
print(f"Linear Regression - Train RMSE: {train_rmse:.3f}, Valid RMSE: {val_rmse:.3f}")


# --- Cell 79 ---
# Create DataFrame with predictions for visualization
val_results = X_val[['date', 'counter_name']].copy()
val_results['actual'] = y_val_log.values
val_results['predicted'] = y_pred_val_linear
val_results = val_results.sort_values('date')

print(f"Validation period: {val_results['date'].min()} to {val_results['date'].max()}")
print(f"Number of observations: {len(val_results):,}")


# --- Cell 81 ---
feature_cols = ["hour", "weekday", "month", "season", "t", "u", "ff", "td", "rr1", "pmer", "weekend", "FR_holidays"]
X_train_base = X_train.copy()
X_train_base = X_train_base[feature_cols]
X_val_base = X_val.copy()
X_val_base = X_val_base[feature_cols]


# --- Cell 82 ---

model = LinearRegression()
model.fit(X_train_base, y_train_log)
y_val_base = model.predict(X_val_base)
y_train_base = model.predict(X_train_base)


# --- Cell 84 ---
plt.scatter(y_val_log, y_pred_val_linear, c=y_val_raw, cmap='viridis', alpha=0.7)
plt.xlabel("Acutal bike counts")
plt.ylabel("predicted bike counts")
plt.title("Actual vs Predicted")
plt.plot([y_val_log.min(), y_val_log.max()], [y_val_log.min(), y_val_log.max()], 'r--', label='Perfect Prediction')
plt.legend()

plt.show()


# --- Cell 87 ---
# Plot 1: Time series for a specific counter
sample_counter = val_results['counter_name'].iloc[0]
counter_data = val_results[val_results['counter_name'] == sample_counter].sort_values('date')

fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(counter_data['date'], counter_data['actual'], label='Actual', alpha=0.7, linewidth=1.5)
ax.plot(counter_data['date'], counter_data['predicted'], label='Predicted', alpha=0.7, linewidth=1.5, linestyle='--')
ax.set_xlabel('Date', fontsize=12)
ax.set_ylabel('Bike Count', fontsize=12)
ax.set_title(f'Actual vs Predicted Bike Counts Over Time\nCounter: {sample_counter}', fontsize=14)
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# --- Cell 90 ---
# Plot 2: Aggregated time series (sum across all counters)
daily_agg = val_results.groupby('date').agg({
    'actual': 'sum',
    'predicted': 'sum'
}).reset_index()

fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(daily_agg['date'], daily_agg['actual'], label='Actual (Total)', alpha=0.7, linewidth=2)
ax.plot(daily_agg['date'], daily_agg['predicted'], label='Predicted (Total)', alpha=0.7, linewidth=2, linestyle='--')
ax.set_xlabel('Date', fontsize=12)
ax.set_ylabel('Total Bike Count (All Counters)', fontsize=12)
ax.set_title('Aggregated Actual vs Predicted Bike Counts\n(Sum Across All Counters)', fontsize=14)
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# --- Cell 94 ---
# Plot 3: Zoom in on a specific week for detailed view
start_date = val_results['date'].min()
end_date = start_date + pd.Timedelta("7 days")
week_data = val_results[(val_results['date'] >= start_date) & (val_results['date'] < end_date)]

# Aggregate by hour for cleaner plot
hourly_agg = week_data.groupby(['date']).agg({
    'actual': 'sum',
    'predicted': 'sum'
}).reset_index()

fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(hourly_agg['date'], hourly_agg['actual'], label='Actual', alpha=0.7, linewidth=2, marker='o', markersize=4)
ax.plot(hourly_agg['date'], hourly_agg['predicted'], label='Predicted', alpha=0.7, linewidth=2, linestyle='--', marker='s', markersize=4)
ax.set_xlabel('Date', fontsize=12)
ax.set_ylabel('Total Bike Count (All Counters)', fontsize=12)
ax.set_title(f'First Week of Validation Period\n{start_date.date()} to {end_date.date()}', fontsize=14)
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# --- Cell 99 ---
# XGBoost Regressor
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.3,
    max_depth=10,
)

pipe_xgb = make_pipeline(preprocessor, xgb_model)
pipe_xgb.fit(X_train, y_train_log)
y_pred_train_xgb = pipe_xgb.predict(X_train)
y_pred_val_xgb = pipe_xgb.predict(X_val)

xgb_r2 = r2_score(y_val_log, y_pred_val_xgb)


print("="*50)
print("XGBOOST REGRESSOR - Model Performance")
print("="*50)
print(f"R² Score:  {xgb_r2:.4f}")


# --- Cell 100 ---
plt.figure(figsize=(8,6))
plt.scatter(y_val_log, y_pred_val_xgb, c=y_val_raw, cmap='viridis', alpha=0.7)
plt.xlabel("Actual bike counts")
plt.ylabel("predicted bike counts")
plt.title("XGBoost: Actual vs Predicted")
plt.plot([y_val_log.min(), y_val_log.max()], [y_val_log.min(), y_val_log.max()], 'r--', label='Perfect Prediction')
plt.legend()
plt.show()


# --- Cell 105 ---
pipe = make_pipeline(preprocessor, Ridge())
pipe.fit(X_train, y_train_log)
y_pred_train_ridge = pipe.predict(X_train)
y_pred_val_ridge = pipe.predict(X_val)


# --- Cell 112 ---
print(
    f"Train set, RMSE={root_mean_squared_error(y_train_log, pipe.predict(X_train)):.2f}"
)
print(
    f"Valid set, RMSE={root_mean_squared_error(y_val_log, pipe.predict(X_val)):.2f}"
)


# --- Cell 119 ---
'''print("Baseline mean prediction.")
print(
    f"Train set, RMSE={root_mean_squared_error(y_train_log, np.full(y_train_.shape, y_train_log.mean())):.2f}"
)
print(
    f"Test set, RMSE={root_mean_squared_error(y_val, np.full(y_val.shape, y_valid.mean())):.2f}"
)''' 
# I think I fucked this a bit up


# --- Cell 128 ---
### 6.5 Visual Inspection of Predictions

# First, calculate the correction factor from training residuals
y_pred_train_log = pipe.predict(X_train)
residuals_train = y_train_log - y_pred_train_log
sigma_squared = np.var(residuals_train)
correction_factor = np.exp(sigma_squared / 2)

print(f"σ² = {sigma_squared:.4f}")
print(f"Jensen correction factor = {correction_factor:.4f}")

# Filter for one counter and one week
mask = (
    (X_val["counter_name"] == "Totem 73 boulevard de Sébastopol S-N") 
    & (X_val["date"] > pd.to_datetime("2021/09/01")) 
    & (X_val["date"] < pd.to_datetime("2021/09/08"))
)

X_viz = X_val[mask].copy()
y_viz_log = y_val_log.loc[mask] if hasattr(y_val_log, 'loc') else pd.Series(y_val_log, index=X_val.index).loc[mask]

# Actual bike counts
X_viz["bike_count"] = np.exp(y_viz_log.values) - 1

# Predictions
y_pred_log = pipe.predict(X_viz)

# Back-transform WITH Jensen correction
X_viz["predicted_naive"] = np.exp(y_pred_log) - 1
X_viz["predicted_corrected"] = np.exp(y_pred_log) * correction_factor - 1

# Plot
fig, ax = plt.subplots(figsize=(14, 5))

X_viz.plot(x="date", y="bike_count", ax=ax, label="Actual", linewidth=2, color='black')
X_viz.plot(x="date", y="predicted_naive", ax=ax, ls="--", label="Predicted (naive)", alpha=0.7)
X_viz.plot(x="date", y="predicted_corrected", ax=ax, ls="--", label=f"Predicted (Jensen corrected ×{correction_factor:.3f})", linewidth=2)

ax.set_title("Ridge Predictions vs Actual - One Week at Sébastopol")
ax.set_ylabel("Bike Count")
ax.set_xlabel("Date")
ax.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Print comparison
print(f"\nMean actual:              {X_viz['bike_count'].mean():.1f}")
print(f"Mean predicted (naive):    {X_viz['predicted_naive'].mean():.1f}")
print(f"Mean predicted (corrected): {X_viz['predicted_corrected'].mean():.1f}")


# --- Cell 136 ---
from sklearn.model_selection import TimeSeriesSplit
cv = TimeSeriesSplit(n_splits=6)
scores = cross_val_score(
    pipe, X_train, y_train_log, cv=cv, scoring="neg_root_mean_squared_error"
)
print("RMSE: ", scores)
print(f"RMSE (all folds): {-scores.mean():.3} ± {(-scores).std():.3}")


# --- Cell 141 ---
alphas = np.logspace(-4, 4, 100)

ridge_cv = RidgeCV(alphas=alphas, cv=5)  # 5-fold cross-validation
pipe = make_pipeline(preprocessor, ridge_cv)
pipe.fit(X_train, y_train_log)

print(f"Best alpha: {pipe.named_steps['ridgecv'].alpha_:.4f}")
print(f"Valid RMSE: {root_mean_squared_error(y_val_log, pipe.predict(X_val)):.3f}")


# --- Cell 148 ---
regressor = DecisionTreeRegressor(max_depth=15, random_state=42)
pipe = make_pipeline(preprocessor, regressor)

pipe.fit(X_train, y_train_log)

print(f"Train RMSE = {root_mean_squared_error(y_train_log, pipe.predict(X_train)):.2f}")
print(f"Valid RMSE = {root_mean_squared_error(y_val_log, pipe.predict(X_val)):.2f}")


# --- Cell 156 ---
# 2. Tune depth MUCH faster
max_depth_values = range(1, 51, 5)
train_rmse = []
valid_rmse = []

for depth in max_depth_values:
    model = DecisionTreeRegressor(max_depth=depth, random_state=42)
    pipe_tuning = make_pipeline(preprocessor, model)
    pipe_tuning.fit(X_train, y_train_log)

    train_rmse.append(
        root_mean_squared_error(y_train_log, pipe_tuning.predict(X_train))
    )

    valid_rmse.append(
        root_mean_squared_error(y_val_log, pipe_tuning.predict(X_val))
    )


# --- Cell 165 ---
best_depth = 36
regressor = DecisionTreeRegressor(max_depth=best_depth, random_state=42)

pipe_cv = make_pipeline(preprocessor, regressor)

cv = TimeSeriesSplit(n_splits=6)
scores = cross_val_score(pipe_cv, X_train, y_train_log,
                         cv=cv,
                         scoring="neg_root_mean_squared_error")

print("RMSE per fold:", -scores)
print(f"Mean RMSE = {-scores.mean():.3f} ± {(-scores).std():.3f}")


# --- Cell 174 ---
# Refit the model with best depth
regressor = DecisionTreeRegressor(max_depth=best_depth, random_state=42)
pipe_week = make_pipeline(date_encoder, preprocessor, regressor)
pipe_week.fit(X_train, y_train_log)

# Filter visualization period
mask = (
    (X_val["counter_name"] == "Totem 73 boulevard de Sébastopol S-N") &
    (X_val["date"] > "2021-09-01") &
    (X_val["date"] < "2021-09-08")
)

df_viz = X_val.loc[mask].copy()
df_viz["bike_count"] = np.exp(y_val_log[mask]) - 1
df_viz["bike_count_predicted"] = np.exp(pipe.predict(X_val[mask])) - 1

plt.figure(figsize=(12,4))
plt.plot(df_viz["date"], df_viz["bike_count"], label="Actual")
plt.plot(df_viz["date"], df_viz["bike_count_predicted"], "--", label="Predicted")
plt.title("Decision Tree Predictions for Example Week")
plt.ylabel("bike_count")
plt.legend()
plt.show()


# --- Cell 182 ---
from sklearn.ensemble import RandomForestRegressor

preprocessor = ColumnTransformer(
    [
        ("date", OneHotEncoder(handle_unknown="ignore"), date_cols),
        ("cat", categorical_encoder, categorical_cols),
        # ("num", numerical_encoder, numerical_corr_cols), 
        ("binary", "passthrough", binary_cols)
    ]
)

regressor = RandomForestRegressor(random_state=42, max_depth=36, n_estimators=3, n_jobs=-1)

start = time()
pipe = make_pipeline(date_encoder, preprocessor, regressor)
pipe.fit(X_train, y_train)
elapsed_time = time() - start

print(f"Training time for random forest: {elapsed_time:.2f} seconds")
print(f"Train set, RMSE={mean_squared_error(y_train, pipe.predict(X_train), squared=False):.2f}")
print(f"Valid set, RMSE={mean_squared_error(y_valid, pipe.predict(X_valid), squared=False):.2f}")


# --- Cell 186 ---
cv = TimeSeriesSplit(n_splits=6)

scores = cross_val_score(
    pipe, X_train, y_train, cv=cv, scoring="neg_root_mean_squared_error", n_jobs=-1
)
print("RMSE: ", scores)
print(f"RMSE (all folds): {-scores.mean():.3} ± {(-scores).std():.3}")


# --- Cell 192 ---
date_encoder = FunctionTransformer(_encode_dates)
date_cols = _encode_dates(X_train[["date"]]).columns.tolist()
date_cols = [col for col in date_cols if col != "day"]

categorical_encoder = OneHotEncoder(handle_unknown="ignore")
categorical_cols = ["counter_name", "site_name"]

numerical_encoder = make_pipeline(
    SimpleImputer(strategy="mean"),
    StandardScaler())
numerical_corr_cols = ["u", "t", "tx12", "tn12", "rafper", "td", "raf10", "ff", "nnuage3", "vv"]

binary_cols = ["weekend", "FR_holidays"]

preprocessor = ColumnTransformer(
    [
        ("date", OneHotEncoder(handle_unknown="ignore"), date_cols),
        ("cat", categorical_encoder, categorical_cols),
        # ("num", numerical_encoder, numerical_corr_cols), 
        ("binary", "passthrough", binary_cols)
    ]
)

regressor = RandomForestRegressor(random_state=42, max_depth=36, n_estimators=7, n_jobs=-1)

start = time()
pipe = make_pipeline(date_encoder, preprocessor, regressor)
pipe.fit(X_train, y_train)
elapsed_time = time() - start

print(f"Training time for random forest: {elapsed_time:.2f} seconds")
print(f"Train set, RMSE={mean_squared_error(y_train, pipe.predict(X_train), squared=False):.2f}")
print(f"Valid set, RMSE={mean_squared_error(y_valid, pipe.predict(X_valid), squared=False):.2f}")


# --- Cell 200 ---
fig, ax = plt.subplots()

df_viz = pd.DataFrame({"y_true": y_valid, "y_pred": pipe.predict(X_valid)}).sample(
    10000, random_state=0
)

df_viz.plot.scatter(x="y_true", y="y_pred", s=8, alpha=0.1, ax=ax)
ax.set_xlabel("y_true")
ax.set_ylabel("y_pred")
plt.show()


# --- Cell 206 ---
from joblib import dump

model_filename = "model1.joblib"
dump(pipe, model_filename)

print(f"Trained model saved to {model_filename}")


# --- Cell 214 ---
test_data = pd.read_parquet(Path("data") / "final_test.parquet")

def _encode_dates(X):
    X = X.copy()
    X["year"] = X["date"].dt.year
    X["month"] = X["date"].dt.month
    X["day"] = X["date"].dt.day
    X["weekday"] = X["date"].dt.weekday  # 0=Monday, 6=Sunday
    X["hour"] = X["date"].dt.hour
    return X

# Apply date encoding and weekend flag
test_data = test_data.copy()
test_data = _encode_dates(test_data)
test_data["weekend"] = (test_data["weekday"] > 4).astype(int)

print(f"minimum date: {test_data['date'].min()}")
print(f"maximum date: {test_data['date'].max()}")

import holidays

FR_holidays = holidays.FR(years=range(2019, 2022))
test_data["FR_holidays"] = test_data["date"].dt.date.isin(FR_holidays).astype(int)
print(f"Number of rows marked as holidays: {test_data['FR_holidays'].sum()}")


# --- Cell 226 ---
X_test = test_data

y_pred = pipe.predict(X_test)

results = pd.DataFrame(
    {
        "Id": np.arange(y_pred.shape[0]),
        "log_bike_count": y_pred,
    }
)

results.to_csv("submission1_Forest_d36_n7.csv", index=False)


# --- Cell 234 ---
preprocessor = ColumnTransformer(
    [
        ("date", OneHotEncoder(handle_unknown="ignore"), date_cols),
        ("cat", categorical_encoder, categorical_cols),
        # We follow the final RF setup: no numerical weather features in the preprocessor.
        ("binary", "passthrough", binary_cols),
    ]
)

rf_regressor = RandomForestRegressor(
    random_state=42,
    max_depth=36,
    n_estimators=7,
    n_jobs=-1
)

rf_pipe = make_pipeline(date_encoder, preprocessor, rf_regressor)

tscv = TimeSeriesSplit(n_splits=3)  # fewer splits to limit computation time

scores = cross_val_score(
    rf_pipe,
    X_train,
    y_train,
    cv=tscv,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1,
)

rmse_scores = -scores
print("RMSE per fold:", rmse_scores)
print(f"Mean RMSE = {rmse_scores.mean():.3f} ± {rmse_scores.std():.3f}")


# --- Cell 244 ---
# Define fractions of the training data to use
train_fracs = [0.1, 0.25, 0.5, 0.75, 1.0]

train_rmse = []
valid_rmse = []

for frac in train_fracs:
    n_samples = int(len(X_train) * frac)
    print(f"Training with {n_samples} samples ({frac*100:.0f}% of training data)")

    # Take the earliest n_samples to respect time order
    X_sub = X_train.iloc[:n_samples].copy()
    y_sub = y_train[:n_samples].copy()

    # Build a fresh pipeline for each fraction
    rf_regressor = RandomForestRegressor(
        random_state=42,
        max_depth=36,
        n_estimators=7,
        n_jobs=-1,
    )
    rf_pipe = make_pipeline(date_encoder, preprocessor, rf_regressor)

    rf_pipe.fit(X_sub, y_sub)

    # RMSE on the subset used for training
    y_sub_pred = rf_pipe.predict(X_sub)
    train_rmse.append(mean_squared_error(y_sub, y_sub_pred, squared=False))

    # RMSE on the fixed validation set
    y_val_pred = rf_pipe.predict(X_valid)
    valid_rmse.append(mean_squared_error(y_valid, y_val_pred, squared=False))

# Plot learning curve
plt.figure(figsize=(8, 5))
plt.plot(np.array(train_fracs) * 100, train_rmse, marker="o", label="Train RMSE")
plt.plot(np.array(train_fracs) * 100, valid_rmse, marker="o", label="Validation RMSE")
plt.xlabel("Training set size (% of available training data)")
plt.ylabel("RMSE (log_bike_count)")
plt.title("Learning Curve – Random Forest (max_depth=36, n_estimators=7)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()


# End of extracted code
